import 'package:flutter/material.dart';
import 'app_colors.dart';

final darkTheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.dark,
  scaffoldBackgroundColor: const Color(0xFF111318),
  colorScheme: const ColorScheme.dark(
    primary: AppColors.primary,
    secondary: AppColors.secondary,
    surface: Color(0xFF232326),
    onPrimary: Colors.white,
    onSurface: Colors.white,
    surfaceContainer: Color(0xFF232326),
  ),
  appBarTheme: const AppBarTheme(
    centerTitle: false,
    backgroundColor: Color(0xFF111318),
    elevation: 0,
    scrolledUnderElevation: 0,
    titleTextStyle: TextStyle(
      color: Colors.white,
      fontSize: 20,
      fontWeight: FontWeight.w700,
      letterSpacing: -0.3,
    ),
    iconTheme: IconThemeData(color: Colors.white, size: 24),
  ),
  cardTheme: CardThemeData(
    color: const Color(0xFF232326),
    elevation: 0,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(28),
      side: BorderSide.none,
    ),
    margin: EdgeInsets.zero,
    shadowColor: Colors.black,
  ),
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      backgroundColor: AppColors.primary,
      foregroundColor: Colors.white,
      minimumSize: const Size(double.infinity, 56),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      elevation: 8,
      shadowColor: AppColors.primary.withOpacity(0.4),
      textStyle: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, letterSpacing: 0.5),
    ),
  ),
  outlinedButtonTheme: OutlinedButtonThemeData(
    style: OutlinedButton.styleFrom(
      foregroundColor: AppColors.primary,
      minimumSize: const Size(double.infinity, 56),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      side: const BorderSide(color: AppColors.primary, width: 2),
      textStyle: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
    ),
  ),
  inputDecorationTheme: InputDecorationTheme(
    filled: true,
    fillColor: AppColors.darkInput,
    border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none),
    enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none),
    focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: const BorderSide(color: AppColors.primary, width: 2)),
    errorBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: const BorderSide(color: AppColors.danger)),
    labelStyle: const TextStyle(color: AppColors.textSecondary),
    hintStyle: const TextStyle(color: AppColors.textMuted),
    contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 18),
  ),
  dividerTheme: DividerThemeData(color: Colors.white.withOpacity(0.05), thickness: 1),
  chipTheme: ChipThemeData(
    backgroundColor: AppColors.darkCard,
    selectedColor: AppColors.primary.withOpacity(0.2),
    labelStyle: const TextStyle(fontSize: 13, color: Colors.white, fontWeight: FontWeight.w500),
    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
    side: BorderSide.none,
  ),
  switchTheme: SwitchThemeData(
    thumbColor: WidgetStateProperty.resolveWith((s) => s.contains(WidgetState.selected) ? AppColors.primary : Colors.grey.shade600),
    trackColor: WidgetStateProperty.resolveWith((s) => s.contains(WidgetState.selected) ? AppColors.primary.withOpacity(0.3) : Colors.grey.shade800),
  ),
  floatingActionButtonTheme: const FloatingActionButtonThemeData(
    backgroundColor: AppColors.primary,
    foregroundColor: Colors.white,
    elevation: 12,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(18))),
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(color: Color(0xFFFFFFFF), fontWeight: FontWeight.bold, fontSize: 32),
    displayMedium: TextStyle(color: Color(0xFFFFFFFF), fontWeight: FontWeight.bold, fontSize: 28),
    displaySmall: TextStyle(color: Color(0xFFFFFFFF), fontWeight: FontWeight.bold, fontSize: 24),
    headlineMedium: TextStyle(color: Color(0xFFFFFFFF), fontWeight: FontWeight.bold, fontSize: 20),
    titleLarge: TextStyle(color: Color(0xFFFFFFFF), fontWeight: FontWeight.bold, fontSize: 18),
    titleMedium: TextStyle(color: Color(0xFFFFFFFF), fontWeight: FontWeight.w600, fontSize: 16),
    bodyLarge: TextStyle(color: Color(0xFFFFFFFF), fontSize: 16),
    bodyMedium: TextStyle(color: Color(0xFFA0A0A0), fontSize: 14),
    bodySmall: TextStyle(color: Color(0xFFA0A0A0), fontSize: 12),
  ),
);
