// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY935ErPfk2S5xIDdk9uMolDnw5jQ4fPg',
    appId: '1:961928716538:web:9d95dcb0adaaa56c11a943',
    messagingSenderId: '961928716538',
    projectId: 'sparks-invoice',
    authDomain: 'sparks-invoice.firebaseapp.com',
    storageBucket: 'sparks-invoice.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtoNNZrE2WSUjhSsM3ksnlChavHH1wawI',
    appId: '1:961928716538:android:18cff10906af962c11a943',
    messagingSenderId: '961928716538',
    projectId: 'sparks-invoice',
    storageBucket: 'sparks-invoice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHtFSn5bLh7WAoI8xySTslwuu0UtNJiD0',
    appId: '1:961928716538:ios:5f4cbc9acf1a7c0111a943',
    messagingSenderId: '961928716538',
    projectId: 'sparks-invoice',
    storageBucket: 'sparks-invoice.firebasestorage.app',
    iosBundleId: 'com.example.sparksInvoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHtFSn5bLh7WAoI8xySTslwuu0UtNJiD0',
    appId: '1:961928716538:ios:5f4cbc9acf1a7c0111a943',
    messagingSenderId: '961928716538',
    projectId: 'sparks-invoice',
    storageBucket: 'sparks-invoice.firebasestorage.app',
    iosBundleId: 'com.example.sparksInvoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY935ErPfk2S5xIDdk9uMolDnw5jQ4fPg',
    appId: '1:961928716538:web:2cd6ac291d8fde2b11a943',
    messagingSenderId: '961928716538',
    projectId: 'sparks-invoice',
    authDomain: 'sparks-invoice.firebaseapp.com',
    storageBucket: 'sparks-invoice.firebasestorage.app',
  );
}
